### ISSUE TITLE
Are the training parameters provided by you the same as those on the website (https://cleanup.pictures/) ?

### ISSUE THREAD

**Issue by zhouwy19** [saic-mdal/lama#50]
Are the training parameters provided by you the same as those on the website (https://cleanup.pictures/) ? Why do the same pictures and masks have different effects?

**Comment by windj007** [comment]
Hi!

Honestly, I do not know which model is used in Cleanup Pictures. What images and outputs do you compare?

> Why do the same pictures and masks have different effects?

This might be also due to different input resolution - Cleanup Pictures downscale input image to 720p, if I'm not mistaken. Feeding same input image and mask but varying input resolution will definitely result in different outputs.

**Comment by zhouwy19** [comment]
What resolution this repo code will resize the input image to?

**Comment by windj007** [comment]
By default, our `predict.py` does not resize image at all
