### ISSUE TITLE
Invalid signal value

### ISSUE THREAD

**Issue by Sins-code** [saic-mdal/lama#95]
Hello and thank you for your great work. I encountered this error trying to start the predict.py...what does it tell me? Im not quite sure how to react and what to change :D
```
python bin\predict.py model.path=B:\ProgrammierDateiBaum\Bachelor\lama\big-lama indir=B:\ProgrammierDateiBaum\Bachelor\bachelorarbeit\Image_data\lama\In outdir=B:\ProgrammierDateiBaum\Bachelor\bachelorarbeit\Image_data\lama\Out
Detectron v2 is not installed
[2022-02-26 16:09:34,785][saicinpainting.utils][WARNING] - Setting signal 1 handler <function print_traceback_handler at 0x0000028C6828E670>
[2022-02-26 16:09:34,787][__main__][CRITICAL] - Prediction failed due to invalid signal value:
Traceback (most recent call last):
  File "bin\predict.py", line 41, in main
  File "B:\ProgrammierDateiBaum\Bachelor\lama\bin\saicinpainting\utils.py", line 109, in register_debug_signal_handlers
    signal.signal(sig, handler)
  File "B:\Python3\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: invalid signal value
```

Edit: 
I made everything work by outcommenting  `register_debug_signal_handlers()` and changing `device` to `cpu` in the `default.yml` file. It seems like the torch 1.8.0 version does struggle with the cuda version I have?! Im not an expert here...

Im working on a windows machine btw...had some trouble creating the env first, seems like with conda on windows some packages are not available - I switched to a "normal" python version and used pip, then it worked!

I would still like to know what the signal error is and whether torch version 1.8.1 would be sufficient as well, because this version does provide a better cuda support it seems.

**Comment by windj007** [comment]
Hi! Sorry for the late reply!

Afaik, this issue is Windows-specific and should have nothing to do with cuda or torch or any other dependencies.

You can safely comment out ` register_debug_signal_handlers`. We added that function in order to debug certain types of bugs, which were related to random freezes, which do not occur anymore.

I do not have a windows machine at hand, so I cannot resolve that issue constructively.

**Comment by windj007** [comment]
Regarding torch and dependencies.... Again, I do not have much experience with Windows.. but for Linux, torch has its own cuda built-in - so you do not even need to install cuda on a linux machine in order to use gpus.

However, it is necessary to have a separate cuda installation, when you want to build custom extensions to torch from sources (e.g. custom layers). In that case, standalone cuda version should perfectly match the version your torch was built with.

That might be different for windows. Please refer to installation guide: it seems to have special commends on cuda or no-cuda cases for Windows: https://pytorch.org/get-started/locally/

**Comment by Sins-code** [comment]
Great, then I will leave the `register_debug_signal_handlers` outcommented as it is. I will experiment with different torch versions on windows, maybe I can figure out whats going on-but it works either way! Thank you for your help :)
